import { Metadata } from "next";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | Apolast",
  description: "Apolast Terms of Service for enterprise legacy modernization software and services.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#FAFAFA]">
      <Navbar />

      <section className="pt-40 pb-20 md:pt-48 md:pb-28">
        <div className="max-w-[800px] mx-auto px-6 sm:px-8">
          <h1 className="text-[clamp(3rem,5vw,4.5rem)] font-bold text-[#111111] leading-[1.1] tracking-tight mb-8">
            Terms of Service
          </h1>
          <div className="mb-12 w-24 h-[6px] bg-[#2FCA54]"></div>

          <div className="space-y-10 text-[17px] leading-[1.7] text-[#333333]">
            {/* 1 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">1. Definitions and Interpretation</h2>
              <p className="mb-4">1.1 In these Terms of Service (“Terms”):</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li><strong>a) “Apolast”</strong> means the Apolast research and development entity organized as a limited liability company (ТОВ) under the laws of Ukraine, together with any affiliated holding or contracting entities identified in an Order Form or Enterprise Agreement.</li>
                <li><strong>b) “Customer”</strong> means the business entity purchasing a license and subscription to the Software, as identified in the Order Form.</li>
                <li><strong>c) “Software”</strong> means the proprietary Apolast platform, including its Abstract Syntax Tree (“AST”) parsers, orchestration frameworks, ensemble of Small Language Models (“SLMs”), CI/CD hooks, integrations and documentation, deployed on‑premise within Customer’s infrastructure.</li>
                <li><strong>d) “Services”</strong> means implementation, setup/audit, integration, training, support, compliance tooling and other professional services provided by Apolast under an Order Form.</li>
                <li><strong>e) “Order Form”</strong> means a written or electronic ordering document executed by both Parties specifying the Subscription Term, license metrics, fees and any special conditions.</li>
                <li><strong>f) “Subscription Term”</strong> means the initial and any renewal term of Customer’s subscription as stated in the Order Form.</li>
                <li><strong>g) “Customer Codebase”</strong> means Customer’s proprietary legacy source code, monolithic architectures, configuration files and related artifacts provided within Customer’s own environment for analysis and transformation by the Software.</li>
                <li><strong>h) “AI‑Generated Output” or “Generated Code”</strong> means microservices, refactored code, tests, architectural blueprints, specifications, Software Bills of Materials (SBOMs) and related artifacts generated by or through the Software based on the Customer Codebase.</li>
                <li><strong>i) “On‑Premise Deployment”</strong> means installation and operation of the Software entirely within Customer’s closed, private or isolated infrastructure, without transmission of Customer Codebase or end‑user data to Apolast servers or public cloud LLMs.</li>
                <li><strong>j) “Applicable Data Protection Laws”</strong> means all laws governing personal data processing, including the General Data Protection Regulation (EU) 2016/679 (“GDPR”) and equivalent or supplemental laws in relevant jurisdictions.</li>
                <li><strong>k) “DORA”</strong> means Regulation (EU) 2022/2554 on digital operational resilience for the financial sector, together with applicable regulatory technical standards.</li>
                <li><strong>l) “NIS2”</strong> means Directive (EU) 2022/2555 on measures for a high common level of cybersecurity across the Union, including Article 21 on supply‑chain security.</li>
              </ul>
              <p>1.2 Headings are for convenience only and do not affect interpretation. Words in the singular include the plural and vice versa.</p>
            </div>

            {/* 2 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">2. Basis of Contract and Scope</h2>
              <p className="mb-4">2.1 These Terms, together with the Order Form and any schedules (including SLA and Data Processing Agreement, where applicable), form the entire agreement between Apolast and Customer for the licensing and use of the Software and provision of the Services.</p>
              <p className="mb-4">2.2 In case of conflict between these Terms and an Order Form, the Order Form shall prevail solely with respect to the conflicting provisions.</p>
              <p className="mb-4">2.3 The Software and Services are provided exclusively on a business‑to‑business (B2B) basis and are not intended for consumer use.</p>
              <p>2.4 The Agreement is structured to support hybrid B2B monetization with a one‑time setup/audit fee and annual recurring subscription (ARR) based on lines of code (LoC) or developer seats.</p>
            </div>

            {/* 3 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">3. License Grant and Restrictions</h2>
              <p className="mb-4">3.1 Subject to Customer’s continuous compliance with these Terms and timely payment of all fees, Apolast grants Customer a limited, non‑exclusive, non‑transferable (except as permitted in Clause 15), non‑sublicensable, revocable license during the Subscription Term to:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) install, configure and operate the Software solely within Customer’s On‑Premise Deployment environment;</li>
                <li>b) use the Software for internal business purposes to audit, map and modernize the Customer Codebase, generate AI‑Generated Output, and maintain architectural visibility;</li>
                <li>c) permit authorized employees, contractors and service providers of Customer to access and use the Software solely for Customer’s benefit and in accordance with these Terms.</li>
              </ul>
              <p className="mb-4">3.2 License metrics (e.g. number of seats, environments, LoC, instances) are specified in the Order Form. Customer shall not exceed licensed metrics without purchasing additional capacity or entering into an amended Order Form.</p>
              <p className="mb-4">3.3 Customer shall not, and shall not permit any third party to:</p>
              <ul className="list-none space-y-3 pl-4">
                <li>a) use the Software to offer a competing service or in a service‑bureau or managed‑service capacity, except where explicitly authorized for System Integrators in a white‑label or project‑based agreement;</li>
                <li>b) reverse‑engineer, decompile, disassemble or attempt to derive the source code or underlying model weights of the Software or SLMs, except to the limited extent allowed by mandatory law;</li>
                <li>c) circumvent license enforcement, capacity tracking or security controls embedded in the Software;</li>
                <li>d) remove or alter proprietary notices or trademarks;</li>
                <li>e) use the Software in violation of any Applicable Data Protection Laws or export control laws.</li>
              </ul>
            </div>

            {/* 4 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">4. Delivery, Deployment and Customer Environment</h2>
              <p className="mb-4">4.1 Following execution of the Order Form and payment of the initial setup fee, Apolast will make the Software packages and documentation available for On‑Premise Deployment.</p>
              <p className="mb-4">4.2 Customer is solely responsible for:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) provisioning suitable hardware (including GPUs or accelerators for SLM inference), operating systems and network configurations;</li>
                <li>b) securing its infrastructure (e.g. identity management, network segmentation, firewalls, backup and recovery);</li>
                <li>c) integrating the Software into its CI/CD pipelines, task management systems and monitoring tools, in accordance with documentation.</li>
              </ul>
              <p>4.3 Because the Software operates entirely within Customer’s closed infrastructure, Customer maintains full operational control over its deployment, access rights and environment configuration.</p>
            </div>

            {/* 5 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">5. Intellectual Property Rights</h2>
              <p className="mb-4">5.1 Apolast retains all right, title and interest, including all intellectual property rights, in and to:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) the Software, including its AST parsers, SLM ensemble, orchestration frameworks, “Living Graph” capabilities and CI/CD hooks;</li>
                <li>b) any generic templates, models, tools, methodologies and documentation used to deliver the Services;</li>
                <li>c) Apolast trade names, trademarks, logos and branding.</li>
              </ul>
              <p className="mb-4">5.2 Customer retains all right, title and interest, including intellectual property rights, in and to:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) the Customer Codebase;</li>
                <li>b) AI‑Generated Output and resulting refactored applications, subject only to Apolast’s rights in the underlying Software and any embedded third‑party/open‑source components.</li>
              </ul>
              <p className="mb-4">5.3 To the extent AI‑Generated Output includes third‑party or open‑source components, such components remain subject to their respective license terms, as disclosed in documentation or SBOM outputs.</p>
              <p>5.4 No rights are granted by implication. Except as expressly stated, neither Party acquires any rights to the other Party’s intellectual property.</p>
            </div>

            {/* 6 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">6. Services, Service Levels and Support</h2>
              <p className="mb-4">6.1 Apolast may provide implementation, audit, integration, training, premium support and compliance advisory Services as described in the Order Form and its schedules.</p>
              <p className="mb-4">6.2 Any Service Level Agreement (SLA) relating to support (e.g. response and resolution times) or maintenance shall be set out in a separate SLA schedule and incorporated by reference.</p>
              <p className="mb-4">6.3 Unless expressly agreed, SLAs apply to support services and not to performance, correctness or particular business outcomes of AI‑Generated Output.</p>
              <p>6.4 Customer shall provide reasonable cooperation, secure remote access (where agreed), information and test environments required for Apolast to deliver the Services.</p>
            </div>

            {/* 7 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">7. Fees, Payment and Taxes</h2>
              <p className="mb-4">7.1 Customer shall pay:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) a one‑time setup/audit fee as described in the Order Form;</li>
                <li>b) annual recurring subscription fees (ARR) based on agreed metrics such as LoC or active developer seats;</li>
                <li>c) any agreed professional services fees (e.g. integration, training, premium support).</li>
              </ul>
              <p className="mb-4">7.2 Unless otherwise stated in the Order Form:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) subscription fees are invoiced in advance of each Subscription Term;</li>
                <li>b) invoices are payable within thirty (30) days of the invoice date;</li>
                <li>c) fees are exclusive of taxes; Customer is responsible for any VAT, sales, use or similar taxes.</li>
              </ul>
              <p>7.3 If Customer fails to pay amounts when due, Apolast may charge interest at the maximum rate permitted by law and, after prior written notice and a cure period, suspend access to the Software or Services.</p>
            </div>

            {/* 8 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">8. Compliance Tooling (DORA, NIS2, SBOM)</h2>
              <p className="mb-4">8.1 The Parties acknowledge that the Software is intended to function as a compliance‑enabling tool, helping Customers subject to DORA to maintain real‑time visibility into IT assets, dependencies and change histories.</p>
              <p className="mb-4">8.2 The Software can generate dynamic SBOMs and related outputs to support NIS2 supply‑chain security and documentation requirements, including component inventories, vulnerability tracking and supplier risk assessments.</p>
              <p>8.3 Apolast does not warrant or guarantee that use of the Software or Services alone will cause Customer to be compliant with DORA, NIS2, PCI DSS, CRA or any other regulatory framework; Customer remains solely responsible for its overall compliance program.</p>
            </div>

            {/* 9 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">9. Data Protection, “Private AI” and Security</h2>
              <p className="mb-4">9.1 Each Party shall comply with Applicable Data Protection Laws in connection with personal data processed under or in relation to these Terms.</p>
              <p className="mb-4">9.2 Default on‑premise model:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) Customer acts as data controller for personal data contained in its systems, logs and Codebase;</li>
                <li>b) the Software processes such data within Customer’s infrastructure under Customer’s exclusive control;</li>
                <li>c) Apolast does not routinely access or process Customer’s end‑user personal data or proprietary code on Apolast‑controlled servers under the default configuration.</li>
              </ul>
              <p className="mb-4">9.3 “Private AI” and Zero Data Retention:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) the SLM ensemble runs locally; Customer Codebase and end‑user data are not transmitted to public cloud LLMs;</li>
                <li>b) Apolast does not use Customer Codebase or end‑user data to train or improve public LLMs;</li>
                <li>c) any temporary access or storage of customer data for support is minimized, strictly controlled and time‑bound.</li>
              </ul>
              <p className="mb-4">9.4 If Customer opts into outbound telemetry or remote support, the Parties will enter into a Data Processing Agreement (DPA) describing roles, purposes, legal bases, security measures, international transfers and retention periods in accordance with GDPR.</p>
              <p>9.5 Apolast will implement appropriate technical and organizational measures to protect any personal data it processes, consistent with GDPR principles of data minimisation, integrity, confidentiality and accountability.</p>
            </div>

            {/* 10 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">10. Customer Responsibilities</h2>
              <p className="mb-4">10.1 Customer is responsible for:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) validating, testing and reviewing AI‑Generated Output and refactored services before deployment;</li>
                <li>b) maintaining backup, disaster recovery and business continuity arrangements;</li>
                <li>c) configuring and enforcing access controls, encryption and security policies in its own environment;</li>
                <li>d) ensuring that its use of the Software, Services and AI‑Generated Output complies with all applicable laws, internal policies and industry standards.</li>
              </ul>
              <p>10.2 Apolast shall have no liability for failures or incidents resulting from Customer’s environment, configuration, or deployment choices, including untested changes to production systems.</p>
            </div>

            {/* 11 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">11. Warranties</h2>
              <p className="mb-4">11.1 Apolast warrants that:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) it has the authority to grant the license and provide the Services;</li>
                <li>b) the Software, when used in accordance with its documentation, will materially conform to its published specifications during the Subscription Term.</li>
              </ul>
              <p className="mb-4">11.2 Except as expressly stated, the Software and Services are provided “as is” and “as available”. Apolast disclaims all other warranties, whether express, implied or statutory, including implied warranties of merchantability, fitness for a particular purpose and non‑infringement.</p>
              <p className="mb-4">11.3 Apolast does not warrant that:</p>
              <ul className="list-none space-y-3 pl-4">
                <li>a) AI‑Generated Output will be error‑free or free of vulnerabilities;</li>
                <li>b) use of the Software will result in any specific business outcome, performance improvement or regulatory status.</li>
              </ul>
            </div>

            {/* 12 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">12. Limitation of Liability</h2>
              <p className="mb-4">12.1 To the maximum extent permitted by law, Apolast’s aggregate liability arising out of or in connection with these Terms, the Software, Services or AI‑Generated Output shall not exceed the total fees paid by Customer to Apolast under the relevant Order Form in the twelve (12) months preceding the event giving rise to the claim.</p>
              <p className="mb-4">12.2 Apolast shall not be liable for any:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) loss of profits, revenue, business, goodwill or data;</li>
                <li>b) indirect, consequential, incidental, special or punitive damages;</li>
                <li>c) loss resulting from Customer’s failure to test AI‑Generated Output or to implement appropriate controls and governance over system changes.</li>
              </ul>
              <p>12.3 These exclusions and limitations apply regardless of the form of action (contract, tort, statute or otherwise), even if Apolast has been advised of the possibility of such damages, except to the extent such limitation is prohibited by applicable law.</p>
            </div>

            {/* 13 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">13. Indemnities</h2>
              <p className="mb-4">13.1 Apolast IP indemnity: Apolast will defend Customer against third‑party claims alleging that the unmodified Software infringes a valid copyright or patent in the jurisdiction specified in the Order Form, and will pay damages finally awarded or agreed in settlement, subject to Clause 12.</p>
              <p className="mb-4">13.2 Apolast’s obligations do not apply to claims arising from:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) combinations of the Software with products or services not provided by Apolast;</li>
                <li>b) modifications made by Customer or on its behalf;</li>
                <li>c) use of the Software after Apolast has provided a non‑infringing replacement.</li>
              </ul>
              <p>13.3 Customer indemnity: Customer will defend and indemnify Apolast against claims arising from Customer Codebase, AI‑Generated Output or Customer’s use of the Software contrary to these Terms or applicable laws, including data protection and intellectual property laws.</p>
            </div>

            {/* 14 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">14. Term, Termination and Suspension</h2>
              <p className="mb-4">14.1 These Terms come into effect on the effective date of the first Order Form and continue for the Subscription Term and any renewals.</p>
              <p className="mb-4">14.2 Either Party may terminate:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) for convenience, with effect at the end of the then‑current Subscription Term, by providing written notice within the period specified in the Order Form;</li>
                <li>b) for material breach not cured within thirty (30) days of written notice;</li>
                <li>c) immediately if the other Party becomes insolvent or enters bankruptcy proceedings.</li>
              </ul>
              <p className="mb-4">14.3 On termination or expiry:</p>
              <ul className="list-none space-y-3 pl-4 mb-4">
                <li>a) Customer’s license to the Software shall automatically cease;</li>
                <li>b) Customer shall uninstall or disable the Software, save for archival copies required by law or audit;</li>
                <li>c) Customer retains ownership of its Customer Codebase and AI‑Generated Output.</li>
              </ul>
              <p>14.4 Apolast may suspend Customer’s access to the Software or Services for material non‑payment or serious security risk, following prior notice and an opportunity to cure.</p>
            </div>

            {/* 15 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">15. Assignment, Subcontracting and Third‑Party Beneficiaries</h2>
              <p className="mb-4">15.1 Customer may not assign or transfer these Terms without Apolast’s prior written consent, except to an affiliate or in connection with a merger or sale of substantially all assets, subject to notice.</p>
              <p className="mb-4">15.2 Apolast may subcontract or use affiliates to perform any part of the Services, remaining responsible for their acts and omissions.</p>
              <p>15.3 These Terms do not confer any rights on third parties, save that Apolast affiliates may benefit from limitations of liability and IP protections.</p>
            </div>

            {/* 16 */}
            <div>
              <h2 className="text-2xl font-bold text-[#111111] mb-4">16. Governing Law, Jurisdiction and Miscellaneous</h2>
              <p className="mb-4">16.1 Governing law and jurisdiction shall be specified in the Order Form. Contracts with foreign Enterprise clients are typically entered into by an Apolast holding or contracting entity (e.g., a US C-Corp or UK Ltd) subject to the laws of its respective jurisdiction (e.g., Delaware, New York, or England and Wales). The Ukrainian LLC (ТОВ) acts exclusively as an R&D center.</p>
              <p className="mb-4">16.2 No waiver of any provision shall be effective unless in writing. If any provision is found invalid or unenforceable, the remainder shall continue in full force.</p>
              <p className="mb-4">16.3 These Terms may only be varied in writing signed or electronically accepted by both Parties.</p>
              <p>16.4 A severability and “entire agreement” clause shall be interpreted to preserve the rest of the Agreement if any clause is held invalid.</p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
